name: Cleanup Expired Content

on:
  schedule:
    # Run daily at midnight EST (5:00 AM UTC during EST)
    - cron: '0 5 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  cleanup-expired:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Log cleanup start
        run: |
          echo "Starting content cleanup at $(TZ='America/New_York' date)"
          echo "Removing articles older than 7 days"
      
      - name: Remove expired content
        run: npm run cleanup-expired
      
      - name: Commit cleanup changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - Cleanup"
          git add .
          if git diff --staged --quiet; then
            echo "No expired content to remove"
          else
            git commit -m "Cleanup expired content - $(TZ='America/New_York' date '+%Y-%m-%d')"
            git push
          fi