name: Daily Content Fetching - 8AM EST

on:
  schedule:
    # 8:00 AM EST = 1:00 PM UTC (during standard time)
    - cron: '0 13 * * *'
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  fetch-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Log current time
        run: |
          echo "UTC Time: $(date -u)"
          echo "EST Time: $(TZ='America/New_York' date)"
          echo "Should be 8:00 AM EST"
      
      - name: Fetch new articles
        run: |
          echo "Fetching articles at $(TZ='America/New_York' date)"
          npm run fetch-articles
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      
      - name: Classify content with AI
        run: npm run classify-content
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
      
      - name: Remove duplicate articles
        run: npm run deduplicate-content
      
      - name: Commit new content
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action - Daily Content"
          git add .
          if git diff --staged --quiet; then
            echo "No new content to commit"
          else
            git commit -m "Daily content update - $(TZ='America/New_York' date '+%Y-%m-%d %I:%M %p EST')"
            git push
          fi
      
      - name: Trigger site rebuild
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main'  // This ensures the workflow is triggered on the current branch
            });